# -*- coding: utf-8 -*-
"""Generate Data Dummy Dashboard Karyawan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxVkhr79h1uOv9F-zNDmieuAErTJkjeP

Data Karyawan
"""

import pandas as pd
import numpy as np
import random
import datetime
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Kunci generator acak agar hasil data selalu konsisten
np.random.seed(2026)
random.seed(2026)

# ---- 1. POOL DATA & ATRIBUT UTAMA ----
NAMA_DEPAN = ["Andi", "Budi", "Chandra", "Dedi", "Eka", "Fajar", "Gilang", "Hendra", "Indra", "Joko",
              "Kurnia", "Laksana", "Mega", "Nadia", "Oki", "Putra", "Rian", "Siti", "Taufik", "Utami",
              "Sanjaya", "Pratama", "Hidayat", "Setiawan", "Lestari", "Anwar", "Gunawan", "Rahma", "Saputra"]
NAMA_BELAKANG = ["Wijaya", "Santoso", "Sutrisno", "Purnama", "Subagyo", "Mahendra", "Prakoso", "Kusuma",
                 "Nugroho", "Wibowo", "Hadi", "Riyadi", "Siregar", "Batubara", "Nasution", "Fauzi", "Asmara"]

DOMISILI_POOL = ["Jakarta Pusat", "Jakarta Selatan", "Jakarta Barat", "Jakarta Timur", "Jakarta Utara",
                 "Bogor", "Depok", "Tangerang", "Bekasi"]
AGAMA_POOL = ["Islam", "Kristen", "Katolik", "Hindu", "Buddha", "Khonghucu"]
JEKEL_POOL = ["Laki-laki", "Perempuan"]

DEPARTEMEN_POOL = [
    "human empowerment & development", "engineering", "service excellence",
    "marketing & business development", "business analyst", "quality & planning control",
    "finance, accounting & tax"
]

# ---- 2. FUNGSI PENJADWALAN KUOTA PERIODE (Maks Masuk 3, Keluar 1) ----
def get_periode_key(date):
    # Cut-off tanggal 21. Jika > 21, masuk ke periode bulan berikutnya
    if date.day > 21:
        if date.month == 12:
            return (date.year + 1, 1)
        return (date.year, date.month + 1)
    return (date.year, date.month)

# Tracker kuota per periode
kuota_masuk = {}
kuota_keluar = {}

def validasi_dan_set_tanggal(tipe="masuk", tahun_start=2015, tahun_end=2025):
    while True:
        thn = random.randint(tahun_start, tahun_end)
        bln = random.randint(1, 12)
        tgl = random.randint(1, 28)
        dt = datetime.date(thn, bln, tgl)
        p_key = get_periode_key(dt)

        if tipe == "masuk":
            if kuota_masuk.get(p_key, 0) < 3:
                kuota_masuk[p_key] = kuota_masuk.get(p_key, 0) + 1
                return dt
        elif tipe == "keluar":
            if kuota_keluar.get(p_key, 0) < 1:
                kuota_keluar[p_key] = kuota_keluar.get(p_key, 0) + 1
                return dt

# ---- 3. GENERATION GENERATOR NAMA UNIK & NRP ----
nama_terpakai = set()
def generate_nama_unik():
    while True:
        nama = f"{random.choice(NAMA_DEPAN)} {random.choice(NAMA_BELAKANG)}"
        if nama not in nama_terpakai:
            nama_terpakai.add(nama)
            return nama

nrp_terpakai = set()
def generate_nrp(tahun_join):
    thn_str = str(tahun_join)[-2:]
    while True:
        rand_num = random.randint(1, 200)
        nrp = f"ABC{thn_str}{rand_num:03d}"
        if nrp not in nrp_terpakai:
            nrp_terpakai.add(nrp)
            return nrp

# ---- 4. PROSES GENERATE DATA KARYAWAN (TOTAL 180 DATA) ----
karyawan_list = []

# --- KELOMPOK A: DATA AWAL PENDIRIAN (1 JULI 2010) ---
# 4 Direksi Awal
for _ in range(4):
    tgl_masuk = datetime.date(2010, 7, 1)
    thn_lahir = random.randint(1965, 1980) # Umur matang saat masuk
    karyawan_list.append({
        'NRP': generate_nrp(2010), 'Nama Lengkap': generate_nama_unik(), 'Status': 'Aktif',
        'Jenis Kelamin': random.choice(JEKEL_POOL), 'Pendidikan Terakhir': random.choice(["S1", "S2"]),
        'Alamat Domisili': random.choice(DOMISILI_POOL), 'Agama': random.choice(AGAMA_POOL),
        'Tanggal Lahir': datetime.date(thn_lahir, random.randint(1,12), random.randint(1,28)).strftime('%Y-%m-%d'),
        'Departemen': 'direksi', 'Tanggal Masuk': tgl_masuk.strftime('%Y-%m-%d'), 'Tanggal Resign': '-',
        'Status Karyawan': 'pkwtt', 'Level Position': 'direksi', 'Status Kerja': 'non-shift'
    })

# 46 Karyawan Awal (Staff s.d. Manager)
dept_alokasi_awal = DEPARTEMEN_POOL * 6 + random.sample(DEPARTEMEN_POOL, 4) # Distribusi rata 46 orang
for dept in dept_alokasi_awal:
    tgl_masuk = datetime.date(2010, 7, 1)
    thn_lahir = random.randint(1980, 1991) # Minimal 19 tahun ke atas pada 2010
    karyawan_list.append({
        'NRP': generate_nrp(2010), 'Nama Lengkap': generate_nama_unik(), 'Status': 'Aktif',
        'Jenis Kelamin': random.choice(JEKEL_POOL), 'Pendidikan Terakhir': random.choice(["SMA", "SMK", "D3", "S1", "S2"]),
        'Alamat Domisili': random.choice(DOMISILI_POOL), 'Agama': random.choice(AGAMA_POOL),
        'Tanggal Lahir': datetime.date(thn_lahir, random.randint(1,12), random.randint(1,28)).strftime('%Y-%m-%d'),
        'Departemen': dept, 'Tanggal Masuk': tgl_masuk.strftime('%Y-%m-%d'), 'Tanggal Resign': '-',
        'Status Karyawan': 'pkwtt', 'Level Position': random.choice(['staff', 'staff', 'supervisor', 'manager']), 'Status Kerja': 'non-shift'
    })

# Sisa kuota data yang harus digenerate: 180 - 50 = 130 data harian dinamis.
# Kita rancang agar 70 orang dari sisa ini berstatus RESIGN (40 Magang, 30 Karyawan).

# --- KELOMPOK B: 40 ANAK MAGANG/PKL RESIGN (2015 - 2025) ---
for _ in range(40):
    tgl_masuk = validasi_dan_set_tanggal("masuk", 2015, 2025)
    # Magang biasanya 3 bulan, kita buat tanggal resign-nya dan validasi kuota keluar
    tgl_out = tgl_masuk + datetime.timedelta(days=90)
    p_out_key = get_periode_key(tgl_out)

    # Pasangkan dengan slot kuota keluar terdekat jika penuh
    while kuota_keluar.get(p_out_key, 0) >= 1:
        tgl_out += datetime.timedelta(days=1)
        p_out_key = get_periode_key(tgl_out)
    kuota_keluar[p_out_key] = kuota_keluar.get(p_out_key, 0) + 1

    thn_lahir = tgl_masuk.year - random.randint(19, 22) # Mahasiswa magang umur 19+
    karyawan_list.append({
        'NRP': generate_nrp(tgl_masuk.year), 'Nama Lengkap': generate_nama_unik(), 'Status': 'Tidak Aktif',
        'Jenis Kelamin': random.choice(JEKEL_POOL), 'Pendidikan Terakhir': random.choice(["SMA", "SMK", "D3", "S1"]),
        'Alamat Domisili': random.choice(DOMISILI_POOL), 'Agama': random.choice(AGAMA_POOL),
        'Tanggal Lahir': datetime.date(thn_lahir, random.randint(1,12), random.randint(1,28)).strftime('%Y-%m-%d'),
        'Departemen': random.choice(DEPARTEMEN_POOL), 'Tanggal Masuk': tgl_masuk.strftime('%Y-%m-%d'), 'Tanggal Resign': tgl_out.strftime('%Y-%m-%d'),
        'Status Karyawan': 'pkwt', 'Level Position': 'staff', 'Status Kerja': 'non-shift'
    })

# --- KELOMPOK C: 30 KARYAWAN RESIGN (2015 - 2025) ---
for _ in range(30):
    tgl_masuk = validasi_dan_set_tanggal("masuk", 2012, 2024)
    tgl_out = validasi_dan_set_tanggal("keluar", 2015, 2025)
    if tgl_out <= tgl_masuk:
        tgl_out = tgl_masuk + datetime.timedelta(days=random.randint(200, 500))

    thn_lahir = tgl_masuk.year - random.randint(23, 40)
    karyawan_list.append({
        'NRP': generate_nrp(tgl_masuk.year), 'Nama Lengkap': generate_nama_unik(), 'Status': 'Tidak Aktif',
        'Jenis Kelamin': random.choice(JEKEL_POOL), 'Pendidikan Terakhir': random.choice(["SMA", "SMK", "D3", "S1", "S2"]),
        'Alamat Domisili': random.choice(DOMISILI_POOL), 'Agama': random.choice(AGAMA_POOL),
        'Tanggal Lahir': datetime.date(thn_lahir, random.randint(1,12), random.randint(1,28)).strftime('%Y-%m-%d'),
        'Departemen': random.choice(DEPARTEMEN_POOL), 'Tanggal Masuk': tgl_masuk.strftime('%Y-%m-%d'), 'Tanggal Resign': tgl_out.strftime('%Y-%m-%d'),
        'Status Karyawan': random.choice(['pkwt', 'pkwtt']), 'Level Position': random.choice(['staff', 'supervisor']), 'Status Kerja': 'non-shift'
    })

# --- KELOMPOK D: SISA KARYAWAN AKTIF TAMBAHAN (Hingga Total 180) ---
sisa_kuota_aktif = 180 - len(karyawan_list)
for _ in range(sisa_kuota_aktif):
    tgl_masuk = validasi_dan_set_tanggal("masuk", 2015, 2025)
    thn_lahir = tgl_masuk.year - random.randint(21, 35)
    karyawan_list.append({
        'NRP': generate_nrp(tgl_masuk.year), 'Nama Lengkap': generate_nama_unik(), 'Status': random.choice(['Aktif', 'Magang/PKL']),
        'Jenis Kelamin': random.choice(JEKEL_POOL), 'Pendidikan Terakhir': random.choice(["SMA", "SMK", "D3", "S1", "S2"]),
        'Alamat Domisili': random.choice(DOMISILI_POOL), 'Agama': random.choice(AGAMA_POOL),
        'Tanggal Lahir': datetime.date(thn_lahir, random.randint(1,12), random.randint(1,28)).strftime('%Y-%m-%d'),
        'Departemen': random.choice(DEPARTEMEN_POOL), 'Tanggal Masuk': tgl_masuk.strftime('%Y-%m-%d'), 'Tanggal Resign': '-',
        'Status Karyawan': random.choice(['pkwt', 'pkwtt']), 'Level Position': random.choice(['staff', 'supervisor', 'manager']), 'Status Kerja': 'non-shift'
    })

df_master = pd.DataFrame(karyawan_list)

# ---- 5. ENFORCEMENT ATURAN OPERATOR (TOTAL Wajib 12 & Alokasi Departemen) ----
# Ambil karyawan non-direksi berstatus Aktif/Magang untuk dijadikan Operator agar pas 12
idx_bukan_direksi = df_master[(df_master['Level Position'] != 'direksi')].index.tolist()
idx_operator_pilihan = random.sample(idx_bukan_direksi, 12)

# Set 6 Orang di Service Excellence
dept_operator_assignment = ["service excellence"] * 6
# Set 6 sisanya masing-masing 1 ke tiap departemen lain
dept_sisa = [d for d in DEPARTEMEN_POOL if d != "service excellence"]
dept_operator_assignment.extend(dept_sisa)

for i, idx in enumerate(idx_operator_pfilename := idx_operator_pilihan):
    df_master.loc[idx, 'Level Position'] = 'operator'
    df_master.loc[idx, 'Status Kerja'] = 'shift'
    df_master.loc[idx, 'Departemen'] = dept_operator_assignment[i]
    # Koreksi pendidikan operator agar sesuai aturan (SMP-S1)
    df_master.loc[idx, 'Pendidikan Terakhir'] = random.choice(["SMP", "SMA", "SMK", "D3", "S1"])

# ---- 6. FINAL VALIDASI PENDIDIKAN UNTUK LEVEL LAIN ----
for idx, row in df_master.iterrows():
    lvl = row['Level Position']
    if lvl in ['staff', 'supervisor', 'manager']:
        if row['Pendidikan Terakhir'] == 'SMP':
            df_master.loc[idx, 'Pendidikan Terakhir'] = random.choice(["SMA", "SMK", "D3", "S1", "S2"])
    elif lvl == 'direksi':
        if row['Pendidikan Terakhir'] not in ['S1', 'S2']:
            df_master.loc[idx, 'Pendidikan Terakhir'] = random.choice(["S1", "S2"])

# ---- 7. FORMATTING EXCEL & SAVE ----
filename_data = "Data_Karyawan_PT_ABC.xlsx"
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Data_Karyawan"
ws.views.sheetView[0].showGridLines = True

header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers = list(df_master.columns)
ws.append(headers)
for cell in ws[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_master.values, start=2):
    ws.append(list(row_data))
    for col_idx, cell in enumerate(ws[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0:
            cell.fill = zebra_fill

        if headers[col_idx-1] in ['NRP', 'Status', 'Jenis Kelamin', 'Pendidikan Terakhir', 'Tanggal Masuk', 'Tanggal Resign', 'Status Karyawan', 'Level Position', 'Status Kerja', 'Agama']:
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='left', vertical='center')

for col in ws.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 3, 12)

wb.save(filename_data)
print(f"Sukses! Berhasil generate {len(df_master)} baris data karyawan ke file: {filename_data}")

"""Presensi 2025"""

import pandas as pd
import numpy as np
import datetime
import random
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Kunci generator acak agar hasil data selalu konsisten
np.random.seed(2026)
random.seed(2026)

# ---- 1. READ MASTER DATA KARYAWAN VERSI TERBARU ----
try:
    df_karyawan = pd.read_excel("Data_Karyawan_PT_ABC.xlsx")
except FileNotFoundError:
    print("Eror: File 'Data_Karyawan_PT_ABC.xlsx' tidak ditemukan! Pastikan Anda sudah menjalankan script Master Karyawan terlebih dahulu.")
    raise

# Parameter Acuan Waktu Baru (8 Jam Kerja termasuk Istirahat)
SHIFT_POOL = ["Shift A (06:00 - 14:00)", "Shift B (10:00 - 18:00)", "Shift C (14:00 - 22:00)"]
OFFICE_HOURS_POOL = ["08:00 - 17:00", "09:00 - 18:00"]

# ---- DATA RESMI LIBUR NASIONAL & CUTI BERSAMA ----
LIBUR_NASIONAL_2024 = {datetime.date(2024, 12, 25)}
CUTI_BERSAMA_2024 = {datetime.date(2024, 12, 26)}
LIBUR_NASIONAL_2025 = {
    datetime.date(2025, 1, 1), datetime.date(2025, 1, 27), datetime.date(2025, 1, 29),
    datetime.date(2025, 3, 29), datetime.date(2025, 3, 31), datetime.date(2025, 4, 1),
    datetime.date(2025, 4, 18), datetime.date(2025, 4, 20), datetime.date(2025, 5, 1),
    datetime.date(2025, 5, 12), datetime.date(2025, 5, 29), datetime.date(2025, 6, 1),
    datetime.date(2025, 6, 6), datetime.date(2025, 6, 27), datetime.date(2025, 8, 17),
    datetime.date(2025, 9, 5), datetime.date(2025, 12, 25)
}
CUTI_BERSAMA_2025 = {
    datetime.date(2025, 1, 28), datetime.date(2025, 3, 28), datetime.date(2025, 4, 2),
    datetime.date(2025, 4, 3), datetime.date(2025, 4, 4), datetime.date(2025, 4, 7),
    datetime.date(2025, 5, 13), datetime.date(2025, 5, 30), datetime.date(2025, 6, 9),
    datetime.date(2025, 12, 26)
}
ALL_LIBUR_NASIONAL = LIBUR_NASIONAL_2024.union(LIBUR_NASIONAL_2025)
ALL_CUTI_BERSAMA = CUTI_BERSAMA_2024.union(CUTI_BERSAMA_2025)

CUTI_KHUSUS_POOL = ["Cuti Khusus", "Cuti Pernikahan", "Cuti Kematian Kerabat"]

# ---- 2. SIMULASI PEMBUATAN LOG PRESENSI ----
start_date = datetime.date(2024, 12, 21)
end_date = datetime.date(2025, 12, 31)
total_days = (end_date - start_date).days + 1

# Konversi kolom tanggal master agar bersih
df_karyawan['Tgl_Masuk_Dt'] = pd.to_datetime(df_karyawan['Tanggal Masuk'], errors='coerce').dt.date
df_karyawan['Tgl_Resign_Dt'] = pd.to_datetime(df_karyawan['Tanggal Resign'], errors='coerce').dt.date

presensi_rows = []

for day_idx in range(total_days):
    current_date = start_date + datetime.timedelta(days=day_idx)
    is_weekend = current_date.weekday() in [5, 6]
    is_libur = current_date in ALL_LIBUR_NASIONAL
    is_cuti_bersama = current_date in ALL_CUTI_BERSAMA

    # Filter karyawan aktif pada tanggal berjalan
    df_aktif = df_karyawan[
        (df_karyawan['Tgl_Masuk_Dt'] <= current_date) &
        ((df_karyawan['Tgl_Resign_Dt'].isna()) | (df_karyawan['Tgl_Resign_Dt'] >= current_date))
    ]

    # Menentukan list karyawan yang masuk record untuk hari ini
    if is_libur or is_cuti_bersama:
        # 1. Sebagian Operator wajib masuk (Bisa disesuaikan misal disampling atau masuk semua)
        # Di sini diasumsikan seluruh operator tetap terjadwal (WFO), non-operator libur
        df_ops = df_aktif[df_aktif['Level Position'] == 'operator']

        # 2. Maksimal 2 karyawan Engineering piket secara acak
        df_eng_pool = df_aktif[(df_aktif['Departemen'] == 'engineering') & (df_aktif['Level Position'] != 'operator')]
        n_piket = min(len(df_eng_pool), 2)
        df_eng_piket = df_eng_pool.sample(n=n_piket) if n_piket > 0 else pd.DataFrame()

        # Gabungkan data komparasi
        df_hari_ini = pd.concat([df_ops, df_eng_piket]).drop_duplicates(subset=['NRP'])

    elif is_weekend:
        # Akhir pekan reguler: Mayoritas libur total (tidak masuk presensi)
        # KECUALI yang melakukan Perjalanan Dinas Hari Libur (Simulasi sampling acak 3% dari total karyawan aktif)
        p_dinas = 0.03
        n_dinas = int(len(df_aktif) * p_dinas)
        df_hari_ini = df_aktif.sample(n=n_dinas) if n_dinas > 0 else pd.DataFrame()

    else:
        # Hari kerja efektif biasa: Semua karyawan aktif masuk presensi
        df_hari_ini = df_aktif

    # Proses pengisian atribut absensi bagi karyawan yang terjaring di df_hari_ini
    for _, karyawan in df_hari_ini.iterrows():
        nrp = karyawan['NRP']
        nama = karyawan['Nama Lengkap']
        dept = karyawan['Departemen']
        status_kerja = karyawan['Status Kerja']
        level_pos = karyawan['Level Position']
        jenkel = karyawan['Jenis Kelamin']

        jam_in, jam_out, remarks = "-", "-", "WFO"

        # Menentukan base jam kerja operasional
        if status_kerja == 'shift':
            jadwal_shift = random.choice(SHIFT_POOL)
            if "Shift A" in jadwal_shift: base_in, base_out = 6, 14
            elif "Shift B" in jadwal_shift: base_in, base_out = 10, 18
            else: base_in, base_out = 14, 22
        else:
            jadwal_office = random.choice(OFFICE_HOURS_POOL)
            base_in = 8 if "08:00" in jadwal_office else 9
            base_out = 17 if base_in == 8 else 18

        # ----------------------------------------------------
        # KONDISI A: LOGIKA UNTUK TANGGAL MERAH (LIBUR NASIONAL / CUTI BERSAMA)
        # ----------------------------------------------------
        if is_libur or is_cuti_bersama:
            if level_pos == 'operator':
                remarks = "WFO"
                jam_in = f"{base_in:02d}:{random.randint(0,15):02d}"
                jam_out = f"{base_out:02d}:{random.randint(0,30):02d}"
            else:
                remarks = "Perjalanan Dinas Hari Libur"
                jam_in = f"{base_in:02d}:00"
                jam_out = f"{base_out:02d}:00"

        # ----------------------------------------------------
        # KONDISI B: LOGIKA UNTUK WEEKEND REGULER (SABTU & MINGGU)
        # ----------------------------------------------------
        elif is_weekend:
            remarks = "Perjalanan Dinas Hari Libur"
            jam_in = f"{random.randint(8,10):02d}:{random.choice([0,15,30]):02d}"
            jam_out = f"{random.randint(15,17):02d}:{random.choice([0,15,30]):02d}"

        # ----------------------------------------------------
        # KONDISI C: LOGIKA HARI KERJA EFEKTIF BIASA
        # ----------------------------------------------------
        else:
            # Penambahan opsi "Izin Satu Hari" ke dalam daftar remarks
            p_remarks = ['WFO', 'Terlambat', 'Perjalanan Dinas', 'Sakit SKD', 'Sakit Non-SKD', 'Cuti Tahunan', 'Izin Setengah Hari', 'Izin Satu Hari', 'Cuti Khusus']
            weights = [0.83, 0.04, 0.03, 0.02, 0.01, 0.02, 0.02, 0.02, 0.01]  # Total bobot disesuaikan tetap 1.0

            if jenkel == 'Perempuan':
                p_remarks.append('Cuti Menstruasi')
                weights = [0.82, 0.04, 0.03, 0.02, 0.01, 0.02, 0.02, 0.02, 0.01, 0.01]

            chosen_remark = np.random.choice(p_remarks, p=weights)

            if chosen_remark == 'WFO':
                remarks = "WFO"
                jam_in = f"{base_in:02d}:{random.randint(0,15):02d}"
                jam_out = f"{base_out:02d}:{random.randint(0,30):02d}"
            elif chosen_remark == 'Terlambat':
                remarks = "Terlambat"
                jam_in = f"{base_in:02d}:{random.randint(16,45):02d}"
                jam_out = f"{base_out:02d}:00"
            elif chosen_remark == 'Perjalanan Dinas':
                if status_kerja == 'non-shift':
                    remarks = "Perjalanan Dinas"
                    jam_in = f"{base_in:02d}:00"; jam_out = f"{base_out:02d}:00"
                else:
                    remarks = "WFO"
                    jam_in = f"{base_in:02d}:{random.randint(0,15):02d}"
                    jam_out = f"{base_out:02d}:{random.randint(0,20):02d}"
            elif chosen_remark == 'Izin Setengah Hari':
                remarks = "Izin Setengah Hari"
                jam_potong = random.randint(1, 4)
                tipe_izin = random.choice(['awal', 'akhir'])
                if tipe_izin == 'awal':
                    jam_in = f"{base_in + jam_potong:02d}:00"; jam_out = f"{base_out:02d}:00"
                else:
                    jam_in = f"{base_in:02d}:00"; jam_out = f"{base_out - jam_potong:02d}:00"
            elif chosen_remark == 'Cuti Khusus':
                remarks = random.choice(CUTI_KHUSUS_POOL)
            elif chosen_remark == 'Izin Satu Hari':
                remarks = "Izin Satu Hari"
                # jam_in dan jam_out tetap "-" sesuai nilai default awal
            else:
                remarks = chosen_remark

        presensi_rows.append({
            'NRP': nrp,
            'Nama Karyawan': nama,
            'Departemen': dept,
            'Tanggal Check In': current_date.strftime('%Y-%m-%d'),
            'Jam Check In': jam_in,
            'Jam Check Out': jam_out,
            'Remarks': remarks,
            'Status Kerja': status_kerja
        })

df_presensi = pd.DataFrame(presensi_rows)

# ---- 3. EXCEL BUILDING & PROFESSIONAL STYLING ----
filename_presensi = "Presensi_PT_ABC.xlsx"
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Log_Presensi"
ws.views.sheetView[0].showGridLines = True

header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers_presensi = list(df_presensi.columns)
ws.append(headers_presensi)
for cell in ws[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_presensi.values, start=2):
    ws.append(list(row_data))
    for col_idx, cell in enumerate(ws[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0:
            cell.fill = zebra_fill

        if headers_presensi[col_idx-1] in ['Tanggal Check In', 'NRP', 'Status Kerja', 'Jam Check In', 'Jam Check Out', 'Remarks']:
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='left', vertical='center')

for col in ws.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 3, 12)

wb.save(filename_presensi)
print(f"Sukses! Log Presensi terbaru berhasil disimpan ke file: {filename_presensi}")

"""Permohonan"""

import pandas as pd
import numpy as np
import datetime
import random
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Kunci generator acak agar hasil data selalu konsisten
np.random.seed(2026)
random.seed(2026)

# ==============================================================================
# ---- 1. READ MASTER DATA KARYAWAN ----
# ==============================================================================
try:
    df_karyawan = pd.read_excel("Data_Karyawan_PT_ABC.xlsx")
except FileNotFoundError:
    print("Eror: File 'Data_Karyawan_PT_ABC.xlsx' tidak ditemukan! Pastikan Anda sudah menjalankan script Master Karyawan terlebih dahulu.")
    raise

# Parameter Acuan Waktu Baru (8 Jam Kerja termasuk Istirahat)
SHIFT_POOL = ["Shift A (06:00 - 14:00)", "Shift B (10:00 - 18:00)", "Shift C (14:00 - 22:00)"]
OFFICE_HOURS_POOL = ["08:00 - 17:00", "09:00 - 18:00"]

# ---- DATA RESMI LIBUR NASIONAL & CUTI BERSAMA ----
LIBUR_NASIONAL_2024 = {datetime.date(2024, 12, 25)}
CUTI_BERSAMA_2024 = {datetime.date(2024, 12, 26)}
LIBUR_NASIONAL_2025 = {
    datetime.date(2025, 1, 1), datetime.date(2025, 1, 27), datetime.date(2025, 1, 29),
    datetime.date(2025, 3, 29), datetime.date(2025, 3, 31), datetime.date(2025, 4, 1),
    datetime.date(2025, 4, 18), datetime.date(2025, 4, 20), datetime.date(2025, 5, 1),
    datetime.date(2025, 5, 12), datetime.date(2025, 5, 29), datetime.date(2025, 6, 1),
    datetime.date(2025, 6, 6), datetime.date(2025, 6, 27), datetime.date(2025, 8, 17),
    datetime.date(2025, 9, 5), datetime.date(2025, 12, 25)
}
CUTI_BERSAMA_2025 = {
    datetime.date(2025, 1, 28), datetime.date(2025, 3, 28), datetime.date(2025, 4, 2),
    datetime.date(2025, 4, 3), datetime.date(2025, 4, 4), datetime.date(2025, 4, 7),
    datetime.date(2025, 5, 13), datetime.date(2025, 5, 30), datetime.date(2025, 6, 9),
    datetime.date(2025, 12, 26)
}
ALL_LIBUR_NASIONAL = LIBUR_NASIONAL_2024.union(LIBUR_NASIONAL_2025)
ALL_CUTI_BERSAMA = CUTI_BERSAMA_2024.union(CUTI_BERSAMA_2025)

CUTI_KHUSUS_POOL = ["Cuti Khusus", "Cuti Pernikahan", "Cuti Kematian Kerabat"]

# ==============================================================================
# ---- 2. SIMULASI PEMBUATAN LOG PRESENSI ----
# ==============================================================================
start_date = datetime.date(2024, 12, 21)
end_date = datetime.date(2025, 12, 31)
total_days = (end_date - start_date).days + 1

df_karyawan['Tgl_Masuk_Dt'] = pd.to_datetime(df_karyawan['Tanggal Masuk'], errors='coerce').dt.date
df_karyawan['Tgl_Resign_Dt'] = pd.to_datetime(df_karyawan['Tanggal Resign'], errors='coerce').dt.date

presensi_rows = []

for day_idx in range(total_days):
    current_date = start_date + datetime.timedelta(days=day_idx)
    is_weekend = current_date.weekday() in [5, 6]
    is_libur = current_date in ALL_LIBUR_NASIONAL
    is_cuti_bersama = current_date in ALL_CUTI_BERSAMA

    df_aktif = df_karyawan[
        (df_karyawan['Tgl_Masuk_Dt'] <= current_date) &
        ((df_karyawan['Tgl_Resign_Dt'].isna()) | (df_karyawan['Tgl_Resign_Dt'] >= current_date))
    ]

    if is_libur or is_cuti_bersama:
        df_ops = df_aktif[df_aktif['Level Position'] == 'operator']
        df_eng_pool = df_aktif[(df_aktif['Departemen'] == 'engineering') & (df_aktif['Level Position'] != 'operator')]
        n_piket = min(len(df_eng_pool), 2)
        df_eng_piket = df_eng_pool.sample(n=n_piket) if n_piket > 0 else pd.DataFrame()

        df_hari_ini = pd.concat([df_ops, df_eng_piket]).drop_duplicates(subset=['NRP'])

    elif is_weekend:
        p_dinas = 0.03
        n_dinas = int(len(df_aktif) * p_dinas)
        df_hari_ini = df_aktif.sample(n=n_dinas) if n_dinas > 0 else pd.DataFrame()

    else:
        df_hari_ini = df_aktif

    for _, karyawan in df_hari_ini.iterrows():
        nrp = karyawan['NRP']
        nama = karyawan['Nama Lengkap']
        dept = karyawan['Departemen']
        status_kerja = karyawan['Status Kerja']
        level_pos = karyawan['Level Position']
        jenkel = karyawan['Jenis Kelamin']

        jam_in, jam_out, remarks = "-", "-", "WFO"

        if status_kerja == 'shift':
            jadwal_shift = random.choice(SHIFT_POOL)
            if "Shift A" in jadwal_shift: base_in, base_out = 6, 14
            elif "Shift B" in jadwal_shift: base_in, base_out = 10, 18
            else: base_in, base_out = 14, 22
        else:
            jadwal_office = random.choice(OFFICE_HOURS_POOL)
            base_in = 8 if "08:00" in jadwal_office else 9
            base_out = 17 if base_in == 8 else 18

        if is_libur or is_cuti_bersama:
            if level_pos == 'operator':
                remarks = "WFO"
                jam_in = f"{base_in:02d}:{random.randint(0,15):02d}"
                jam_out = f"{base_out:02d}:{random.randint(0,30):02d}"
            else:
                remarks = "Perjalanan Dinas Hari Libur"
                jam_in = f"{base_in:02d}:00"
                jam_out = f"{base_out:02d}:00"

        elif is_weekend:
            remarks = "Perjalanan Dinas Hari Libur"
            jam_in = f"{random.randint(8,10):02d}:{random.choice([0,15,30]):02d}"
            jam_out = f"{random.randint(15,17):02d}:{random.choice([0,15,30]):02d}"

        else:
            p_remarks = ['WFO', 'Terlambat', 'Perjalanan Dinas', 'Sakit SKD', 'Sakit Non-SKD', 'Cuti Tahunan', 'Izin Setengah Hari', 'Izin Satu Hari', 'Cuti Khusus']
            weights = [0.83, 0.04, 0.03, 0.02, 0.01, 0.02, 0.02, 0.02, 0.01]

            if jenkel == 'Perempuan':
                p_remarks.append('Cuti Menstruasi')
                weights = [0.82, 0.04, 0.03, 0.02, 0.01, 0.02, 0.02, 0.02, 0.01, 0.01]

            chosen_remark = np.random.choice(p_remarks, p=weights)

            if chosen_remark == 'WFO':
                remarks = "WFO"
                jam_in = f"{base_in:02d}:{random.randint(0,15):02d}"
                jam_out = f"{base_out:02d}:{random.randint(0,30):02d}"
            elif chosen_remark == 'Terlambat':
                remarks = "Terlambat"
                jam_in = f"{base_in:02d}:{random.randint(16,45):02d}"
                jam_out = f"{base_out:02d}:00"
            elif chosen_remark == 'Perjalanan Dinas':
                if status_kerja == 'non-shift':
                    remarks = "Perjalanan Dinas"
                    jam_in = f"{base_in:02d}:00"; jam_out = f"{base_out:02d}:00"
                else:
                    remarks = "WFO"
                    jam_in = f"{base_in:02d}:{random.randint(0,15):02d}"
                    jam_out = f"{base_out:02d}:{random.randint(0,20):02d}"
            elif chosen_remark == 'Izin Setengah Hari':
                remarks = "Izin Setengah Hari"
                jam_potong = random.randint(1, 4)
                tipe_izin = random.choice(['awal', 'akhir'])
                if tipe_izin == 'awal':
                    # Izin di jam awal masuk, baru datang siang
                    jam_in = f"{base_in + jam_potong:02d}:00"
                    jam_out = f"{base_out:02d}:00"
                else:
                    # Masuk pagi normal, pulang dipercepat siang/sore
                    jam_in = f"{base_in:02d}:00"
                    jam_out = f"{base_out - jam_potong:02d}:00"
            elif chosen_remark == 'Cuti Khusus':
                remarks = random.choice(CUTI_KHUSUS_POOL)
            elif chosen_remark == 'Izin Satu Hari':
                remarks = "Izin Satu Hari"
            else:
                remarks = chosen_remark

        presensi_rows.append({
            'NRP': nrp,
            'Nama Karyawan': nama,
            'Departemen': dept,
            'Tanggal Check In': current_date.strftime('%Y-%m-%d'),
            'Jam Check In': jam_in,
            'Jam Check Out': jam_out,
            'Remarks': remarks,
            'Status Kerja': status_kerja
        })

df_presensi = pd.DataFrame(presensi_rows)

# ---- SAVE PRESENSI TO EXCEL ----
filename_presensi = "Presensi_PT_ABC.xlsx"
wb_p = openpyxl.Workbook()
ws_p = wb_p.active
ws_p.title = "Log_Presensi"
ws_p.views.sheetView[0].showGridLines = True

header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers_presensi = list(df_presensi.columns)
ws_p.append(headers_presensi)
for cell in ws_p[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_presensi.values, start=2):
    ws_p.append(list(row_data))
    for col_idx, cell in enumerate(ws_p[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0: cell.fill = zebra_fill
        if headers_presensi[col_idx-1] in ['Tanggal Check In', 'NRP', 'Status Kerja', 'Jam Check In', 'Jam Check Out', 'Remarks']:
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='left', vertical='center')

for col in ws_p.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws_p.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 3, 12)

wb_p.save(filename_presensi)
print(f"Sukses! File Presensi berhasil disimpan: {filename_presensi}")


# ==============================================================================
# ---- 3. PROSES EKSTRAKSI REKOR PERMOHONAN (FORM FILING) ----
# ==============================================================================
karyawan_dict = df_karyawan.set_index('NRP').to_dict('index')
levels_weight = {'Operator': 1, 'Staff': 2, 'Supervisor': 3, 'Manager': 4, 'Direksi': 5}

def cari_penyetuju(nrp_pemohon):
    pemohon = karyawan_dict.get(nrp_pemohon)
    if not pemohon: return "HR Department"
    dept_pemohon = pemohon['Departemen']
    level_pemohon = levels_weight.get(pemohon['Level Position'], 1)

    atasan_dept = df_karyawan[(df_karyawan['Departemen'] == dept_pemohon) & (df_karyawan['Status'] == 'Aktif')]
    atasan_valid = [row['Nama Lengkap'] for _, row in atasan_dept.iterrows() if levels_weight.get(row['Level Position'], 1) > level_pemohon]

    if atasan_valid: return random.choice(atasan_valid)

    tim_hed = df_karyawan[(df_karyawan['Departemen'] == 'Human Empowerment & Development') & (df_karyawan['Status'] == 'Aktif') & (df_karyawan['Level Position'].isin(['Staff', 'Supervisor', 'Manager']))]
    if not tim_hed.empty: return random.choice(tim_hed['Nama Lengkap'].tolist())
    return "Direksi HED"

SAKIT_KEYWORDS = ['demam', 'lambung', 'sakit gigi', 'pusing/sakit kepala', 'sakit otot/tulang', 'migrain', 'diare', 'radang tenggorokan', 'alergi', 'sakit mata', 'amandel']
sakit_templates = ["mengalami gejala {} sejak pagi", "ijin karena sakit {}", "kondisi badan {} tidak fit", "perlu istirahat akibat {}", "surat dokter menyatakan {}", "pemulihan medis gejala {}"]
cuti_templates = ["keperluan urusan keluarga besar", "istirahat dan penyegaran piknik", "acara sakral keluarga rumah", "jadwal rutin tahunan keluarga", "memenuhi undangan hajat saudara"]
izin_templates = ["ada urusan perbankan mendesak", "mengurus berkas kependudukan warga", "mengantar orang tua kontrol", "perbaikan kendaraan mogok dijalan", "kondisi darurat rumah tangga"]

def generate_keterangan(jenis):
    if jenis == 'Sakit': kalimat = random.choice(sakit_templates).format(random.choice(SAKIT_KEYWORDS))
    elif jenis == 'Cuti': kalimat = random.choice(cuti_templates)
    elif jenis == 'Izin': kalimat = random.choice(izin_templates)
    else: kalimat = "mengganti kekurangan jam kerja"
    return " ".join(kalimat.split()[:5])

# EKSKLUSI: 'Terlambat' dikeluarkan total dari pembuatan form permohonan
df_non_wfo = df_presensi[~df_presensi['Remarks'].isin(['WFO', 'Perjalanan Dinas', 'Perjalanan Dinas Hari Libur', 'Libur Nasional', 'Terlambat'])].copy()
df_non_wfo['Tanggal Check In'] = pd.to_datetime(df_non_wfo['Tanggal Check In']).dt.date
df_non_wfo = df_non_wfo.sort_values(by=['NRP', 'Tanggal Check In'])

permohonan_list = []
skip_indices = set()
non_wfo_records = df_non_wfo.to_dict('records')

for idx, rec in enumerate(non_wfo_records):
    if idx in skip_indices: continue

    nrp = rec['NRP']
    nama = rec['Nama Karyawan']
    dept = rec['Departemen']
    remarks_awal = rec['Remarks']
    tgl_mulai = rec['Tanggal Check In']
    status_kerja = rec['Status Kerja']

    # Inisialisasi default penanda jam kosong
    waktu_mulai = "-"
    waktu_akhir = "-"

    # Rekonstruksi jadwal base jam kerja untuk menghitung jam absen kosong pada izin hourly
    # Ini menjamin waktu singkron dengan data acuan presensi sebelumnya
    if status_kerja == 'shift':
        # Sampling pendekatan representatif acuan grup shift
        base_in, base_out = 8, 16 # default mid fallback
        if rec['Jam Check In'] != "-" and rec['Jam Check In'].startswith('06'): base_in, base_out = 6, 14
        elif rec['Jam Check In'] != "-" and rec['Jam Check In'].startswith('10'): base_in, base_out = 10, 18
        elif rec['Jam Check In'] != "-" and rec['Jam Check In'].startswith('14'): base_in, base_out = 14, 22
        elif rec['Jam Check Out'] != "-" and rec['Jam Check Out'].startswith('14'): base_in, base_out = 6, 14
        elif rec['Jam Check Out'] != "-" and rec['Jam Check Out'].startswith('18'): base_in, base_out = 10, 18
        elif rec['Jam Check Out'] != "-" and rec['Jam Check Out'].startswith('22'): base_in, base_out = 14, 22
    else:
        base_in = 9 if (rec['Jam Check In'] != "-" and rec['Jam Check In'].startswith('09')) or (rec['Jam Check Out'] != "-" and rec['Jam Check Out'].startswith('18')) else 8
        base_out = 18 if base_in == 9 else 17

    # ---- PROSES LOGIKA DETEKSI JENIS DAN RENTANG WAKTU (HOURLY PERFECTION) ----
    if "Cuti" in remarks_awal:
        jenis, sub_jenis = "Cuti", remarks_awal
    elif "Sakit" in remarks_awal:
        jenis, sub_jenis = "Sakit", ("SKD" if "SKD" in remarks_awal and "Non" not in remarks_awal else "Non SKD")
    elif "Izin Setengah Hari" in remarks_awal:
        jenis, sub_jenis = "Izin", "Izin Hourly"
        # Jika tap-in pagi kosong/terlambat parah karena izin awal
        if rec['Jam Check In'] != f"{base_in:02d}:00" and rec['Jam Check Out'] == f"{base_out:02d}:00":
            waktu_mulai = f"{base_in:02d}:00"      # Mulai meninggalkan jam kerja di awal pagi
            waktu_akhir = rec['Jam Check In']      # Selesai izin saat baru datang absen masuk
        else:
            waktu_mulai = rec['Jam Check Out']     # Mulai izin meninggalkan kantor di siang/sore hari
            waktu_akhir = f"{base_out:02d}:00"     # Berakhir di jam pulang standar kantor

    elif "Izin Satu Hari" in remarks_awal:
        jenis, sub_jenis = "Izin", "Izin Satu Hari"
    elif "Lembur Pengganti" in remarks_awal:
        jenis, sub_jenis = "Jam Pengganti", "Pengganti"
        waktu_mulai = f"{base_out:02d}:00"
        waktu_akhir = rec['Jam Check Out']
    else:
        jenis, sub_jenis = "Izin", "Izin Satu Hari"

    # Logika Menghitung Rentang Hari Bersambung (Multi-day)
    jumlah_hari = 1
    current_date = tgl_mulai
    next_idx = idx + 1

    if sub_jenis not in ["Izin Hourly", "Pengganti"]:
        while next_idx < len(non_wfo_records):
            next_rec = non_wfo_records[next_idx]
            if next_rec['NRP'] == nrp and next_rec['Remarks'] == remarks_awal:
                selisih_hari = (next_rec['Tanggal Check In'] - current_date).days
                if selisih_hari == 1 or (current_date.weekday() == 4 and selisih_hari == 3):
                    jumlah_hari += 1
                    current_date = next_rec['Tanggal Check In']
                    skip_indices.add(next_idx)
                    next_idx += 1
                else: break
            else: break

    # Penyesuaian Tanggal Pengajuan Form yang Realistis
    if jenis == "Sakit": tgl_pengajuan = tgl_mulai + datetime.timedelta(days=random.choice([0, 1]))
    elif jenis == "Cuti": tgl_pengajuan = tgl_mulai - datetime.timedelta(days=random.randint(3, 7))
    else: tgl_pengajuan = tgl_mulai - datetime.timedelta(days=random.choice([0, 1]))

    status_app = "Disetujui" if jenis == "Sakit" else np.random.choice(["Disetujui", "Tidak Disetujui"], p=[0.96, 0.04])
    penyetuju = cari_penyetuju(nrp)
    keterangan = generate_keterangan(jenis)

    permohonan_list.append({
        'NRP': nrp,
        'Nama': nama,
        'Departemen': dept,
        'Status Kerja': status_kerja, # Kolom Baru Ditambahkan Sesuai Permintaan
        'Tanggal Pengajuan': tgl_pengajuan.strftime('%Y-%m-%d'),
        'Jenis': jenis,
        'Sub Jenis': sub_jenis,
        'Keterangan': keterangan,
        'Tanggal Mulai': tgl_mulai.strftime('%Y-%m-%d'),
        'Waktu Mulai': waktu_mulai,   # Sinkron Jam Mulai Izin
        'Waktu Akhir': waktu_akhir,   # Kolom Baru Sinkron Jam Selesai Izin
        'Jumlah Hari': jumlah_hari,
        'Status': status_app,
        'Disetujui Oleh': penyetuju
    })

df_permohonan_final = pd.DataFrame(permohonan_list)

# ==============================================================================
# ---- 4. EXCEL BUILDING FOR DATA PERMOHONAN ----
# ==============================================================================
filename_permohonan = "Data_Permohonan_PT_ABC.xlsx"
wb_o = openpyxl.Workbook()
ws_o = wb_o.active
ws_o.title = "Data_Permohonan"
ws_o.views.sheetView[0].showGridLines = True

headers_permohonan = list(df_permohonan_final.columns)
ws_o.append(headers_permohonan)
for cell in ws_o[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_permohonan_final.values, start=2):
    ws_o.append(list(row_data))
    for col_idx, cell in enumerate(ws_o[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0: cell.fill = zebra_fill

        # Penyelarasan format kolom tengah vs rata kiri
        if headers_permohonan[col_idx-1] in ['NRP', 'Status Kerja', 'Tanggal Pengajuan', 'Jenis', 'Sub Jenis', 'Tanggal Mulai', 'Waktu Mulai', 'Waktu Akhir', 'Jumlah Hari', 'Status']:
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='left', vertical='center')

for col in ws_o.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws_o.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 3, 12)

wb_o.save(filename_permohonan)
print(f"Sukses Sempurna! File '{filename_permohonan}' berhasil diperbarui dengan penambahan Waktu Akhir dan Status Kerja.")

"""Perjalanan Dinas"""

import pandas as pd
import numpy as np
import datetime
import random
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Kunci generator acak agar hasil data selalu konsisten
np.random.seed(2026)
random.seed(2026)

# ---- 1. READ DATAFRAME SEBELUMNYA ----
try:
    df_karyawan = pd.read_excel("Data_Karyawan_PT_ABC.xlsx")
    df_presensi = pd.read_excel("Presensi_PT_ABC.xlsx")
except FileNotFoundError as e:
    print(f"Eror: File tidak ditemukan! Pastikan file master dan presensi sudah ada. {e}")
    raise

# Buat kamus pemetaan NRP ke Jabatan (Level Position)
jabatan_dict = df_karyawan.set_index('NRP')['Level Position'].to_dict()

# ---- DATA RESMI LIBUR NASIONAL & CUTI BERSAMA (DISESUAIKAN) ----
# 2024: Hanya yang terjadi DI ATAS tanggal 20 Desember 2024
LIBUR_NASIONAL_2024 = {
    datetime.date(2024, 12, 25), # Hari Raya Natal
}
CUTI_BERSAMA_2024 = {
    datetime.date(2024, 12, 26), # Cuti Bersama Natal
}

# 2025: Berlaku Penuh Sepanjang Tahun
LIBUR_NASIONAL_2025 = {
    datetime.date(2025, 1, 1), datetime.date(2025, 1, 27), datetime.date(2025, 1, 29),
    datetime.date(2025, 3, 29), datetime.date(2025, 3, 31), datetime.date(2025, 4, 1),
    datetime.date(2025, 4, 18), datetime.date(2025, 4, 20), datetime.date(2025, 5, 1),
    datetime.date(2025, 5, 12), datetime.date(2025, 5, 29), datetime.date(2025, 6, 1),
    datetime.date(2025, 6, 6), datetime.date(2025, 6, 27), datetime.date(2025, 8, 17),
    datetime.date(2025, 9, 5), datetime.date(2025, 12, 25),
}
CUTI_BERSAMA_2025 = {
    datetime.date(2025, 1, 28), datetime.date(2025, 3, 28), datetime.date(2025, 4, 2),
    datetime.date(2025, 4, 3), datetime.date(2025, 4, 4), datetime.date(2025, 4, 7),
    datetime.date(2025, 5, 13), datetime.date(2025, 5, 30), datetime.date(2025, 6, 9),
    datetime.date(2025, 12, 26),
}

ALL_LIBUR_NASIONAL = LIBUR_NASIONAL_2024.union(LIBUR_NASIONAL_2025)
ALL_CUTI_BERSAMA = CUTI_BERSAMA_2024.union(CUTI_BERSAMA_2025)

# ---- 2. BANK DATA KOTA & TEMPLATES KEPERLUAN ----
KOTA_LUAR = ['Kota Bandung', 'Kota Surabaya', 'Kota Semarang', 'Kabupaten Bekasi', 'Kota Tangerang', 'Kota Medan', 'Kota Makassar', 'Kota Denpasar', 'Kota Yogyakarta']
CATEGORIES = ['maintenance', 'meeting', 'update', 'demo/training', 'other']

keperluan_templates = [
    "melakukan kegiatan {} berkala di cabang",
    "menghadiri agenda {} penting dengan klien utama",
    "koordinasi teknis terkait proyek {} sistem operasional",
    "pelaksanaan tugas {} untuk tim operasional lapangan",
    "menyelesaikan urusan {} mendesak bersama tim regional",
    "kunjungan kerja dalam rangka {} rutin tahunan"
]

def generate_keperluan_dan_kota(kategori):
    p_kota = np.random.choice(['Kota Jakarta','Luar Kota'], p=[0.65, 0.35])
    if p_kota == 'Kota Jakarta':
        kota_tujuan, jangkauan = "Kota Jakarta", "Dalam Kota"
    else:
        kota_tujuan = random.choice(KOTA_LUAR)
        jangkauan = "Luar Kota"

    kalimat = random.choice(keperluan_templates).format(kategori)
    words = kalimat.split()
    keperluan = " ".join(words[:10])

    return kota_tujuan, jangkauan, keperluan

# ---- 3. PROSES EKSTRAKSI REKOR PERJALANAN DINAS ----
df_dinas = df_presensi[df_presensi['Remarks'].isin(['Perjalanan Dinas', 'Perjalanan Dinas Hari Libur'])].copy()
df_dinas['Tanggal Check In'] = pd.to_datetime(df_dinas['Tanggal Check In']).dt.date

df_dinas = df_dinas.sort_values(by=['NRP', 'Tanggal Check In'])

dinas_list = []
skip_indices = set()
dinas_records = df_dinas.to_dict('records')

for idx, rec in enumerate(dinas_records):
    if idx in skip_indices:
        continue

    nrp = rec['NRP']
    nama = rec['Nama Karyawan']
    dept = rec['Departemen']
    jabatan = jabatan_dict.get(nrp, 'Staff')
    tgl_berangkat = rec['Tanggal Check In']

    kat_keperluan = random.choice(CATEGORIES)
    kota_tujuan, jangkauan, keperluan = generate_keperluan_dan_kota(kat_keperluan)

    # Logika Penggalian Tipe Hari Berangkat (Kerja vs Libur)
    is_weekend = (tgl_berangkat.weekday() in [5, 6])
    is_libur_nasional = tgl_berangkat in ALL_LIBUR_NASIONAL
    is_cuti_bersama = tgl_berangkat in ALL_CUTI_BERSAMA

    # Aturan baru dieksekusi di sini
    if is_weekend or is_libur_nasional or is_cuti_bersama:
        tipe_hari = "Hari Libur"
    else:
        tipe_hari = "Hari Kerja"

    # Logika menggabungkan hari dinas berturut-turut (Multi-day Trip)
    tgl_pulang = tgl_berangkat
    current_date = tgl_berangkat
    next_idx = idx + 1

    while next_idx < len(dinas_records):
        next_rec = dinas_records[next_idx]
        if next_rec['NRP'] == nrp:
            selisih_hari = (next_rec['Tanggal Check In'] - current_date).days
            if selisih_hari == 1 or selisih_hari == 3:
                tgl_pulang = next_rec['Tanggal Check In']
                current_date = next_rec['Tanggal Check In']
                skip_indices.add(next_idx)
                next_idx += 1
            else:
                break
        else:
            break

    dinas_list.append({
        'NRP': nrp,
        'Nama': nama,
        'Jabatan': jabatan,
        'Departemen': dept,
        'Kota Tujuan': kota_tujuan,
        'Keperluan': keperluan,
        'Kategori Keperluan': kat_keperluan,
        'Tanggal Berangkat': tgl_berangkat.strftime('%Y-%m-%d'),
        'Tanggal Pulang': tgl_pulang.strftime('%Y-%m-%d'),
        'Tipe Hari Berangkat': tipe_hari,
        'Jangkauan': jangkauan
    })

df_dinas_final = pd.DataFrame(dinas_list)

# ---- 4. EXCEL BUILDING & PROFESIONAL STYLING WITH OPENPYXL ----
filename_dinas = "Data_Perjalanan_Dinas_PT_ABC.xlsx"
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Perjalanan_Dinas"
ws.views.sheetView[0].showGridLines = True

header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers_dinas = list(df_dinas_final.columns)
ws.append(headers_dinas)
for cell in ws[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_dinas_final.values, start=2):
    ws.append(list(row_data))
    for col_idx, cell in enumerate(ws[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0:
            cell.fill = zebra_fill

        if headers_dinas[col_idx-1] in ['NRP', 'Jabatan', 'Kota Tujuan', 'Kategori Keperluan', 'Tanggal Berangkat', 'Tanggal Pulang', 'Tipe Hari Berangkat', 'Jangkauan']:
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='left', vertical='center')

for col in ws.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 3, 12)

wb.save(filename_dinas)
print(f"Sukses! Data Perjalanan Dinas berhasil diperbarui dengan filter regulasi libur 2024: {filename_dinas}")

"""Lembur"""

import pandas as pd
import numpy as np
import datetime
import random
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Kunci generator acak agar hasil data selalu konsisten
np.random.seed(2026)
random.seed(2026)

# ---- 1. READ DATAFRAME MASTER KARYAWAN ----
try:
    df_karyawan = pd.read_excel("Data_Karyawan_PT_ABC.xlsx")
except FileNotFoundError:
    print("Eror: File 'Data_Karyawan_PT_ABC.xlsx' tidak ditemukan!")
    raise

# Buat kamus untuk penentuan approval atasan
karyawan_dict = df_karyawan.set_index('NRP').to_dict('index')
levels_weight = {'Operator': 1, 'Staff': 2, 'Supervisor': 3, 'Manager': 4, 'Direksi': 5}

def cari_penyetuju_lembur(nrp_pemohon):
    pemohon = karyawan_dict.get(nrp_pemohon)
    if not pemohon: return "HR Department"

    dept_pemohon = pemohon['Departemen']
    level_pemohon = levels_weight.get(pemohon['Level Position'], 1)

    # Cari atasan langsung di departemen yang sama
    atasan_dept = df_karyawan[(df_karyawan['Departemen'] == dept_pemohon) & (df_karyawan['Status'] == 'Aktif')]
    atasan_valid = [row['Nama Lengkap'] for _, row in atasan_dept.iterrows() if levels_weight.get(row['Level Position'], 1) > level_pemohon]

    if atasan_valid:
        return random.choice(atasan_valid)

    # Jika tidak ada atasan di dept tersebut, dilempar ke Personel HED
    tim_hed = df_karyawan[(df_karyawan['Departemen'] == 'Human Empowerment & Development') &
                          (df_karyawan['Status'] == 'Aktif') &
                          (df_karyawan['Level Position'].isin(['Staff', 'Supervisor', 'Manager']))]
    if not tim_hed.empty:
        return random.choice(tim_hed['Nama Lengkap'].tolist())
    return "Management HEAD"

# ---- 2. BANK DATA KATEGORI & TEMPLATES KETERANGAN LEMBUR ----
CATEGORIES_LEMBUR = ['Bug', 'update', 'adjust', 'baru', 'payment']

keterangan_templates = {
    'Bug': ["perbaikan emergency {} pada sistem inti aplikasi", "fixing {} error transactional server utama", "penanganan kendala {} critical pasca deployment"],
    'update': ["maintenance rutin dan {} core database mingguan", "proses {} migrasi data user platform", "optimasi performa server untuk {} berkala"],
    'adjust': ["proses {} rekonsiliasi saldo akhir laporan bulanan", "sinkronisasi dan {} data internal operasional", "melakukan {} parameter konfigurasi sistem logistik"],
    'baru': ["pengerjaan modul {} untuk kebutuhan ekspansi bisnis", "testing deployment fitur {} di server staging", "implementasi desain {} sistem antrean operator"],
    'payment': ["monitoring kelancaran engine {} gateway saat flash sale", "audit berkas transaksi {} akhir periode kuartal", "troubleshooting kliring sistem {} pending nasabah"]
}

# ---- 3. SIMULASI GENERATE DATA LEMBUR INDEPENDEN (2024 - 2025) ----
start_date = datetime.date(2024, 1, 1)
end_date = datetime.date(2025, 12, 31)
date_range = pd.date_range(start_date, end_date).date

lembur_rows = []

# Kita ambil sampel karyawan aktif secara acak untuk memicu lembur insidentil
karyawan_aktif = df_karyawan[df_karyawan['Status'] == 'Aktif'].to_dict('records')

for tgl in date_range:
    # Anggap setiap harinya ada 1 sampai 4 kejadian lembur di perusahaan secara acak
    jumlah_kejadian_lembur = random.randint(1, 4)

    # Deteksi Weekend / Weekday dari tanggal mulai
    is_weekend = tgl.weekday() in [5, 6]
    tipe_hari = "Weekend" if is_weekend else "Weekday"

    for _ in range(jumlah_kejadian_lembur):
        emp = random.choice(karyawan_aktif)

        # Penentuan Kategori & Kalimat Keterangan (Maksimal 10 kata)
        kategori = random.choice(CATEGORIES_LEMBUR)
        template = random.choice(keterangan_templates[kategori])
        keterangan = template.format(kategori)
        keterangan = " ".join(keterangan.split()[:10]) # Batasi max 10 kata

        # Penentuan Waktu Mulai & Akhir Lembur (Skenario Malam Hari / Lintas Hari)
        # 30% Peluang lembur malam lintas hari, 70% lembur kelar di hari yang sama
        if np.random.rand() > 0.7:
            # Lintas Hari (Contoh: Mulai jam 22:00, selesai jam 02:00 dini hari besoknya)
            jam_mulai_h = random.randint(20, 23)
            jam_akhir_h = random.randint(1, 4)

            waktu_mulai = datetime.time(jam_mulai_h, random.choice([0, 30]))
            waktu_akhir = datetime.time(jam_akhir_h, random.choice([0, 30]))

            tgl_mulai = tgl
            tgl_akhir = tgl + datetime.timedelta(days=1)

            # Hitung Durasi menggunakan datetime gabungan
            dt_mulai = datetime.datetime.combine(tgl_mulai, waktu_mulai)
            dt_akhir = datetime.datetime.combine(tgl_akhir, waktu_akhir)
            durasi_jam = (dt_akhir - dt_mulai).seconds / 3600.0
        else:
            # Selesai di hari yang sama (Contoh: Lembur malam 18:00 - 21:00)
            jam_mulai_h = random.randint(17, 19)
            jam_akhir_h = random.randint(20, 23)

            waktu_mulai = datetime.time(jam_mulai_h, random.choice([0, 30]))
            waktu_akhir = datetime.time(jam_akhir_h, random.choice([0, 30]))

            tgl_mulai = tgl
            tgl_akhir = tgl

            dt_mulai = datetime.datetime.combine(tgl_mulai, waktu_mulai)
            dt_akhir = datetime.datetime.combine(tgl_akhir, waktu_akhir)
            durasi_jam = (dt_akhir - dt_mulai).seconds / 3600.0

        # Penyetuju & Status Approval
        status_app = np.random.choice(["Disetujui", "Tidak Disetujui"], p=[0.90, 0.10])
        penyetuju = cari_penyetuju_lembur(emp['NRP'])

        lembur_rows.append({
            'NRP': emp['NRP'],
            'Nama': emp['Nama Lengkap'],
            'Departemen': emp['Departemen'],
            'Tanggal Mulai': tgl_mulai.strftime('%Y-%m-%d'),
            'Waktu Mulai': waktu_mulai.strftime('%H:%M'),
            'Tanggal Akhir': tgl_akhir.strftime('%Y-%m-%d'),
            'Waktu Akhir': waktu_akhir.strftime('%H:%M'),
            'Durasi Lembur': round(durasi_jam, 1),
            'Status': status_app,
            'Disetujui Oleh': penyetuju,
            'Keterangan': keterangan,
            'Kategori Lembur': kategori,
            'Weekend/Weekday': tipe_hari
        })

df_lembur_final = pd.DataFrame(lembur_rows)

# ---- 4. EXCEL BUILDING & PROFESIONAL STYLING WITH OPENPYXL ----
filename_lembur = "Data_Lembur_PT_ABC.xlsx"
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Data_Lembur"
ws.views.sheetView[0].showGridLines = True

# Palet tema profesional (Slate Blue Theme)
header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers_lembur = list(df_lembur_final.columns)
ws.append(headers_lembur)
for cell in ws[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_lembur_final.values, start=2):
    ws.append(list(row_data))
    for col_idx, cell in enumerate(ws[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0:
            cell.fill = zebra_fill

        # Atur perataan teks
        if headers_lembur[col_idx-1] in ['NRP', 'Tanggal Mulai', 'Waktu Mulai', 'Tanggal Akhir', 'Waktu Akhir', 'Durasi Lembur', 'Status', 'Kategori Lembur', 'Weekend/Weekday']:
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='left', vertical='center')

# Auto-fit lebar kolom
for col in ws.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 3, 12)

wb.save(filename_lembur)
print(f"Sukses! File Excel Data Lembur Berhasil Dibuat: {filename_lembur}")

"""Salary dan Lembur"""

import pandas as pd
import numpy as np
import datetime
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Kunci acak agar hasil tetap konsisten
np.random.seed(2026)

# ---- 1. READ DATAFRAME TERKAIT ----
try:
    df_karyawan = pd.read_excel("Data_Karyawan_PT_ABC.xlsx")
    df_lembur = pd.read_excel("Data_Lembur_PT_ABC.xlsx")
except FileNotFoundError as e:
    print(f"Eror: File master atau data lembur tidak ditemukan! {e}")
    raise

# Konversi kolom tanggal ke format datetime
df_karyawan['Tanggal Masuk'] = pd.to_datetime(df_karyawan['Tanggal Masuk'])
df_karyawan['Tanggal Resign'] = pd.to_datetime(df_karyawan['Tanggal Resign'], errors='coerce')
df_lembur['Tanggal Mulai'] = pd.to_datetime(df_lembur['Tanggal Mulai'])

# ---- 2. ATURAN PASAR GAJI BERDASARKAN UMK Jakarta ----
UMK_Jakarta_2025 = 5729876

# Bobot pengali dasar per level jabatan
level_multipliers = {
    'Operator': 1.0,
    'Staff': 1.4,
    'Supervisor': 2.2,
    'Manager': 4.0,
    'Direksi': 7.0
}

def hitung_gaji_pokok_individu(row, tahun_analisis=2025):
    level = row['Level Position']
    tgl_masuk = row['Tanggal Masuk']

    # Gaji Dasar = Multiplier Level * UMK
    gaji_dasar = level_multipliers.get(level, 1.0) * UMK_Jakarta_2025

    # Hitung masa kerja (Tahun) hingga tahun 2025
    masa_kerja_tahun = max(0, tahun_analisis - tgl_masuk.year)

    # Kenaikan loyalitas/pengalaman kerja (3.5% per tahun masa kerja)
    gaji_akhir = gaji_dasar * (1 + (masa_kerja_tahun * 0.035))

    # Tambahkan sedikit variasi acak industri (noise +- 5%) agar data natural
    variasi = np.random.uniform(0.95, 1.05)

    return round(gaji_akhir * variasi, -3) # Dibulatkan ke ribuan terdekat

# Terapkan perhitungan gaji individu sementara ke df_karyawan
df_karyawan['Gaji_2025'] = df_karyawan.apply(hitung_gaji_pokok_individu, axis=1)

# ---- 3. PROSES AGREGASI BULANAN PERIODE 2025 ----
payroll_summary = []

for bulan in range(1, 13):
    awal_bulan = pd.Timestamp(datetime.date(2025, bulan, 1))
    if bulan == 12:
        akhir_bulan = pd.Timestamp(datetime.date(2025, 12, 31))
    else:
        akhir_bulan = pd.Timestamp(datetime.date(2025, bulan + 1, 1)) - pd.Timedelta(days=1)

    nama_bulan = awal_bulan.strftime('%B 2025')

    # A. Hitung Total Gaji Karyawan yang AKTIF di bulan tersebut
    # Karyawan dihitung berhak digaji jika: Tanggal Masuk <= Akhir Bulan DAN (Tanggal Resign kosong ATAU Tanggal Resign >= Awal Bulan)
    # Karyawan dengan status 'Fiktif' diabaikan
    df_aktif_bulan_ini = df_karyawan[
        (df_karyawan['Status'] != 'Fiktif') &
        (df_karyawan['Tanggal Masuk'] <= akhir_bulan) &
        ((df_karyawan['Tanggal Resign'].isna()) | (df_karyawan['Tanggal Resign'] >= awal_bulan))
    ]

    total_salary_bulan_ini = df_aktif_bulan_ini['Gaji_2025'].sum()

    # B. Hitung Total Kompensasi Lembur Berstatus DISETUJUI pada bulan tersebut
    df_lembur_bulan_ini = df_lembur[
        (df_lembur['Status'] == 'Disetujui') &
        (df_lembur['Tanggal Mulai'] >= awal_bulan) &
        (df_lembur['Tanggal Mulai'] <= akhir_bulan)
    ].copy()

    # Hitung biaya lembur per baris kejadian
    total_overtime_pay_bulan_ini = 0
    for _, row_lembur in df_lembur_bulan_ini.iterrows():
        nrp_lembur = row_lembur['NRP']
        durasi = row_lembur['Durasi Lembur']
        tipe_hari = row_lembur['Weekend/Weekday']

        # Cari komponen gaji pokok individu pemohon lembur untuk menentukan tarif per jam
        info_karyawan = df_karyawan[df_karyawan['NRP'] == nrp_lembur]
        if not info_karyawan.empty:
            gapok = info_karyawan['Gaji_2025'].values[0]
        else:
            gapok = UMK_CIMAHI_2025

        # Rumus upah lembur per jam standar Depnaker RI (Gapok / 173)
        tarif_per_jam_dasar = gapok / 173.0

        # Penentuan faktor pengali berdasarkan tipe hari kerja/libur
        if tipe_hari == 'Weekend':
            biaya_per_kejadian = durasi * tarif_per_jam_dasar * 2.0 # Pengali weekend lebih besar
        else:
            biaya_per_kejadian = durasi * tarif_per_jam_dasar * 1.5

        total_overtime_pay_bulan_ini += biaya_per_kejadian

    payroll_summary.append({
        'Bulan': nama_bulan,
        'Total Salary': round(total_salary_bulan_ini, -3),
        'Total Kompensasi Lembur': round(total_overtime_pay_bulan_ini, -3)
    })

df_payroll_final = pd.DataFrame(payroll_summary)

# ---- 4. EXCEL BUILDING & PROFESIONAL STYLING WITH OPENPYXL ----
filename_payroll = "Summary_Payroll_PT_ABC_2025.xlsx"
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Summary_Payroll_2025"
ws.views.sheetView[0].showGridLines = True

# Palet tema finansial korporat (Navy Midnight Accent)
header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers_payroll = list(df_payroll_final.columns)
ws.append(headers_payroll)
for cell in ws[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_payroll_final.values, start=2):
    ws.append(list(row_data))
    for col_idx, cell in enumerate(ws[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        if row_idx % 2 == 0:
            cell.fill = zebra_fill

        # Atur format perataan & akuntansi finansial Rupiah (Rp)
        if headers_payroll[col_idx-1] == 'Bulan':
            cell.alignment = Alignment(horizontal='center', vertical='center')
        else:
            cell.alignment = Alignment(horizontal='right', vertical='center')
            cell.number_format = '"Rp"#,##0' # Format nominal mata uang di Excel

# Auto-fit lebar kolom agar teks Rp tidak terpotong (###)
for col in ws.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 6, 18)

wb.save(filename_payroll)
print(f"Sukses! Laporan Keuangan Bulanan Berhasil Dibuat: {filename_payroll}")

"""2024"""

import pandas as pd
import numpy as np
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ---- 1. READ DATAFRAME YANG DIBUTUHKAN ----
try:
    df_presensi = pd.read_excel("Presensi_PT_ABC.xlsx")
    df_lembur = pd.read_excel("Data_Lembur_PT_ABC.xlsx")
except FileNotFoundError as e:
    print(f"Eror: File master tidak ditemukan! {e}")
    raise

# Konversi kolom tanggal ke format datetime
df_presensi['Tanggal Check In'] = pd.to_datetime(df_presensi['Tanggal Check In'])
df_lembur['Tanggal Mulai'] = pd.to_datetime(df_lembur['Tanggal Mulai'])

summary_data = []

# Loop untuk memproses tahun 2024 dan 2025
for tahun in [2024, 2025]:
    # Filter data berdasarkan tahun
    df_p_tahun = df_presensi[df_presensi['Tanggal Check In'].dt.year == tahun].copy()
    df_l_tahun = df_lembur[(df_lembur['Tanggal Mulai'].dt.year == tahun) & (df_lembur['Status'] == 'Disetujui')].copy()

    if df_p_tahun.empty:
        continue

    # --- A. PERHITUNGAN PERSENTASE KEHADIRAN ---
    # Total hari efektif kerja adalah hari di mana statusnya bukan Libur Nasional
    total_hari_efektif = df_p_tahun[df_p_tahun['Remarks'] != 'Libur Nasional'].shape[0]

    # Karyawan dianggap hadir jika statusnya WFO, Terlambat, Perjalanan Dinas, atau WFO (Lembur Pengganti)
    total_kehadiran_riil = df_p_tahun[df_p_tahun['Remarks'].isin(['WFO', 'Perjalanan Dinas', 'Terlambat', 'WFO (Lembur Pengganti)'])].shape[0]

    if total_hari_efektif > 0:
        pct_kehadiran = (total_kehadiran_riil / total_hari_efektif) * 100
    else:
        pct_kehadiran = 0

    # --- B. PERHITUNGAN OVERTIME (TOTAL DURASI DESIMAL) ---
    total_overtime_durasi = df_l_tahun['Durasi Lembur'].sum()

    # --- C. PERHITUNGAN JUMLAH TOTAL KASUS ABSENSI ---
    total_terlambat = df_p_tahun[df_p_tahun['Remarks'] == 'Terlambat'].shape[0]
    total_sakit = df_p_tahun[df_p_tahun['Remarks'].str.contains('Sakit', na=False)].shape[0]
    total_izin_full = df_p_tahun[df_p_tahun['Remarks'] == 'Izin Satu Hari'].shape[0]
    total_izin_half = df_p_tahun[df_p_tahun['Remarks'] == 'Izin Setengah Hari'].shape[0]

    # --- D. SIMULASI DEVIASI POPULASI (BERDASARKAN AGREGAT BULANAN) ---
    # Agar nilai deviasi masuk akal terhadap total tahunan, kita hitung standar deviasi dari variasi tren bulanan
    df_p_tahun['Bulan'] = df_p_tahun['Tanggal Check In'].dt.month
    df_l_tahun['Bulan'] = df_l_tahun['Tanggal Mulai'].dt.month

    bulanan_p = df_p_tahun.groupby('Bulan').agg(
        Hadir=('Remarks', lambda x: x.isin(['WFO', 'Perjalanan Dinas', 'Terlambat', 'WFO (Lembur Pengganti)']).sum()),
        Efektif=('Remarks', lambda x: (x != 'Libur Nasional').sum()),
        Terlambat_Count=('Remarks', lambda x: (x == 'Terlambat').sum()),
        Sakit_Count=('Remarks', lambda x: x.str.contains('Sakit', na=False).sum()),
        Izin_Count=('Remarks', lambda x: (x == 'Izin Satu Hari').sum()),
        Izin_Half_Count=('Remarks', lambda x: (x == 'Izin Setengah Hari').sum())
    )
    bulanan_p['Pct'] = (bulanan_p['Hadir'] / bulanan_p['Efektif']) * 100
    bulanan_l = df_l_tahun.groupby('Bulan')['Durasi Lembur'].sum()

    # Hitung standar deviasi (di-scale ke proporsi tahunan agar tidak timpang)
    std_kehadiran = bulanan_p['Pct'].std() if len(bulanan_p) > 1 else 0
    std_overtime = bulanan_l.std() * 2.5 if len(bulanan_l) > 1 else 0
    std_terlambat = bulanan_p['Terlambat_Count'].std() * 2.5 if len(bulanan_p) > 1 else 0
    std_sakit = bulanan_p['Sakit_Count'].std() * 2.5 if len(bulanan_p) > 1 else 0
    std_izin_full = bulanan_p['Izin_Count'].std() * 2.5 if len(bulanan_p) > 1 else 0
    std_izin_half = bulanan_p['Izin_Half_Count'].std() * 2.5 if len(bulanan_p) > 1 else 0

    summary_data.append({
        'Tahun': tahun,
        'Rata-Rata Kehadiran': round(pct_kehadiran, 2),
        'Deviasi Kehadiran': round(std_kehadiran, 2),
        'Overtime': round(total_overtime_durasi, 1),
        'Deviasi Overtime': round(std_overtime, 2),
        'Terlambat': int(total_terlambat),
        'Deviasi Terlambat': round(std_terlambat, 2),
        'Sakit': int(total_sakit),
        'Deviasi Sakit': round(std_sakit, 2),
        'Izin Full Day': int(total_izin_full),
        'Deviasi Izin Full Day': round(std_izin_full, 2),
        'Izin Setengah Hari': int(total_izin_half),
        'Deviasi Izin Setengah Hari': round(std_izin_half, 2)
    })

df_summary_final = pd.DataFrame(summary_data)

# ---- 2. EXCEL BUILDING & PROFESSIONAL STYLING ----
filename_summary = "Summary_Statistik_Tahunan.xlsx"
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Summary_Statistik"
ws.views.sheetView[0].showGridLines = True

# Styling Palet Tema Slate Blue
header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
data_font = Font(name='Segoe UI', size=10, color='000000')
zebra_fill = PatternFill(start_color='F2F6FA', end_color='F2F6FA', fill_type='solid')
thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

headers = list(df_summary_final.columns)
ws.append(headers)

for cell in ws[1]:
    cell.font, cell.fill, cell.alignment = header_font, header_fill, Alignment(horizontal='center', vertical='center', wrap_text=True)

for row_idx, row_data in enumerate(df_summary_final.values, start=2):
    ws.append(list(row_data))
    for col_idx, cell in enumerate(ws[row_idx], start=1):
        cell.font, cell.border = data_font, thin_border
        cell.alignment = Alignment(horizontal='center', vertical='center')
        if row_idx % 2 == 0:
            cell.fill = zebra_fill

        # Atur format angka khusus persentase di kolom Kehadiran
        col_name = headers[col_idx-1]
        if col_name in ['Rata-Rata Kehadiran', 'Deviasi Kehadiran']:
            cell.number_format = '0.00"%"'
        elif col_name in ['Overtime', 'Deviasi Overtime', 'Deviasi Terlambat', 'Deviasi Sakit', 'Deviasi Izin Full Day', 'Deviasi Izin Setengah Hari']:
            cell.number_format = '#,##0.0'
        elif col_name in ['Tahun', 'Terlambat', 'Sakit', 'Izin Full Day', 'Izin Setengah Hari']:
            cell.number_format = '#,##0'

# Autofit kolom
for col in ws.columns:
    max_len = max(len(str(cell.value or '')) for cell in col)
    ws.column_dimensions[get_column_letter(col[0].column)].width = max(max_len + 4, 15)

# Simpan file
wb.save(filename_summary)
print(f"Sukses! File Excel rekapitulasi tahunan berhasil dibuat: {filename_summary}")